"""empty message

Revision ID: 4223c3e8f267
Revises: 001
Create Date: 2024-12-12 19:49:31.658318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4223c3e8f267'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposition_metadata', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('fakenodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fakenodo')
    op.drop_table('deposition')
    # ### end Alembic commands ###
