"""empty message

Revision ID: d83485f4d4af
Revises: 001
Create Date: 2024-12-10 15:42:04.391520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd83485f4d4af'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'])

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.alter_column('number_of_models',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('number_of_features',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.alter_column('number_of_features',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('number_of_models',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    op.drop_table('webhook')
    # ### end Alembic commands ###
