name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  release:
    types: [published]

jobs:

  commits-syntax-checker:
    uses: ./.github/workflows/commits.yml

  lint:
    needs: commits-syntax-checker
    uses: ./.github/workflows/lint.yml

  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml

  codacy:
    needs: tests
    uses: ./.github/workflows/codacy.yml

  deploy-render:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/render.yml

  docker-publish:
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deployment_on_dockerhub.yml
