name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, review_requested, synchronize]
  release:
    types: [published]

jobs:

  commits-syntax-checker:
    uses: ./.github/workflows/commits.yml

  lint:
    needs: commits-syntax-checker
    uses: ./.github/workflows/lint.yml

  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml

  codacy:
    needs: lint
    uses: ./.github/workflows/codacy.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} 


  validate-main-branch:
    name: Validate Main Branch
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: echo "Push to main branch detected."

  deploy-render:
    needs: validate-main-branch
    uses: ./.github/workflows/render.yml
    secrets: 
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  docker-publish:
    needs: validate-main-branch
    uses: ./.github/workflows/deployment_on_dockerhub.yml
