name: Test Python version

on:
  workflow_call:

jobs:
  check:
    name: Test Python version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Tell python versions
        run: |
          python --version
          python3.11 --version

      - name: Try to install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./